name: CMake-CUI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug
  WORK_SPACE: ${{github.workspace}}/project/CrafterraTest-CMake-CUI
  TARGET: CrafterraTest-CMake-CUI

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        mkdir ${{env.WORK_SPACE}}/build
        cmake -B ${{env.WORK_SPACE}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - Unix Makefiles" ${{env.WORK_SPACE}}

    - name: Build
      env:
        CC: ${{matrix.compiler}}
      run: cmake --build ${{env.WORK_SPACE}}/build --config ${{env.BUILD_TYPE}} --target ${{env.TARGET}} -- -j 12
